# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-04-01 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20171007_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ticket_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_category',
            field=models.CharField(blank=True, choices=[('Access Request-BitBucket', 'Access Request-BitBucket'), ('Access Request-VPN', 'Access Request-VPN'), ('Access Request-Mysql/Psql Database', 'Access Request-Mysql/Psql Database'), ('Access Request-Mongo Database', 'Access Request-Mongo Database'), ('Issue-CI/CD Jenkins/Spinnaker', 'Issue-CI/CD Jenkins/Spinnaker'), ('Issue-Grafana/Kibana', 'Issue-Grafana/Kibana'), ('Issue-NonProd', 'Issue-NonProd'), ('Issue-Production', 'Issue-Production'), ('New Service Setup', 'New Service Setup'), ('New-Task/Feature Request', 'New-Task/Feature Request'), ('General Guidance', 'General Guidance')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_em_cc',
            field=models.ManyToManyField(blank=True, related_name='ticket_em_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_priority',
            field=models.CharField(choices=[('P0', 'High'), ('P1', 'Medium'), ('P2', 'Normal')], default='P2', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_summary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
