# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-04-01 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20250401_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_priority', models.CharField(choices=[('P0', 'High'), ('P1', 'Medium'), ('P2', 'Normal')], default='P2', max_length=2)),
                ('ticket_category', models.CharField(blank=True, choices=[('Access Request-BitBucket', 'Access Request-BitBucket'), ('Access Request-VPN', 'Access Request-VPN'), ('Access Request-Mysql/Psql Database', 'Access Request-Mysql/Psql Database'), ('Access Request-Mongo Database', 'Access Request-Mongo Database'), ('Issue-CI/CD Jenkins/Spinnaker', 'Issue-CI/CD Jenkins/Spinnaker'), ('Issue-Grafana/Kibana', 'Issue-Grafana/Kibana'), ('Issue-NonProd', 'Issue-NonProd'), ('Issue-Production', 'Issue-Production'), ('New Service Setup', 'New Service Setup'), ('New-Task/Feature Request', 'New-Task/Feature Request'), ('General Guidance', 'General Guidance')], max_length=100, null=True)),
                ('ticket_summary', models.CharField(blank=True, max_length=256, null=True)),
                ('ticket_description', models.TextField(blank=True, null=True)),
                ('ticket_attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='ticket_attachment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ticket_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ticket_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ticket_em_cc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ticket_priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ticket_summary',
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dashboard.Project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_em_cc',
            field=models.ManyToManyField(blank=True, related_name='ticket_em_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
