# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-04-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20250403_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('OnHold', 'OnHold'), ('InProgress', 'InProgress'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
