# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-04-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
